server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;

    gzip on;
    gzip_min_length 1024;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location /api/admin/hotels {
        proxy_pass http://hotel-service:8080;
        include /etc/nginx/proxy_params;
    }
    location /api/admin/room-types {
        proxy_pass http://hotel-service:8080;
        include /etc/nginx/proxy_params;
    }
    location /api/admin/rates {
        proxy_pass http://rate-service:8080;
        include /etc/nginx/proxy_params;
    }
    location /api/admin/inventory {
        proxy_pass http://reservation-service:8080;
        include /etc/nginx/proxy_params;
    }
    location /api/hotels {
        proxy_pass http://hotel-service:8080;
        include /etc/nginx/proxy_params;
    }
    location /api/rates {
        proxy_pass http://rate-service:8080;
        include /etc/nginx/proxy_params;
    }
    location /api/search {
        proxy_pass http://reservation-service:8080;
        include /etc/nginx/proxy_params;
    }
    location /api/reservations {
        proxy_pass http://reservation-service:8080;
        include /etc/nginx/proxy_params;
    }
    location /images/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
    location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nAllow: /\n";
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
