sonar.organization=marcelomiyake
sonar.projectKey=marcelomiyake_hotel-dry-kiss-yagni-refactored-ddd-cleanarch-cqrs
sonar.projectName=Hotel Reservation System - DDD Clean Architecture CQRS
sonar.sourceEncoding=UTF-8
sonar.java.source=25
sonar.sources=services/common/src/main/java,services/hotel-service/src/main/java,services/rate-service/src/main/java,services/payment-service/src/main/java,services/reservation-service/src/main/java,frontend/src
sonar.tests=services/common/src/test/java,services/hotel-service/src/test/java,services/rate-service/src/test/java,services/payment-service/src/test/java,services/reservation-service/src/test/java,frontend/test
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*Test.java
sonar.java.binaries=services/common/target/classes,services/hotel-service/target/classes,services/rate-service/target/classes,services/payment-service/target/classes,services/reservation-service/target/classes
sonar.java.test.binaries=services/common/target/test-classes,services/hotel-service/target/test-classes,services/rate-service/target/test-classes,services/payment-service/target/test-classes,services/reservation-service/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=services/common/target/site/jacoco/jacoco.xml,services/hotel-service/target/site/jacoco/jacoco.xml,services/rate-service/target/site/jacoco/jacoco.xml,services/payment-service/target/site/jacoco/jacoco.xml,services/reservation-service/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/coverage/**
