sonar.organization=marcelomiyake
sonar.projectKey=marcelomiyake_hotel-dry-kiss-yagni-refactored-ddd-cleanarch-cqrs-rermade-rust
sonar.projectName=Hotel Reservation System - Rust Backend
sonar.sourceEncoding=UTF-8
sonar.sources=services/backend/src,frontend/src
sonar.tests=services/backend/tests,frontend/test
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*_test.rs
sonar.externalIssuesReportPaths=services/backend/target/sonar/rust-issues.json
sonar.coverageReportPaths=services/backend/target/sonar/rust-coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/coverage/**
